apiVersion: v1
kind: Service
metadata:
  name: personality-traits-service
spec:
  selector:
    app: personality-traits
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

